---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos7
    #image: docker.io/pycontribs/centos:7
    #pre_build_image: true
    image: centos:7
    #dockerfile: ../resources/Dockerfile.j2
    privileged: true
    command: /usr/sbin/init

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - destroy
