---
dependency:
  name: galaxy
driver:
  name: docker
platforms:

  - name: centos7
    image: centos:7
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    command: /usr/sbin/init

provisioner:
  name: ansible
verifier:
  name: ansible

